"""Executive Risk Dashboard report (report run --type dashboard).

Pure computed SVG/CSS — gauge, KPI cards, severity donut, category bars, and
remediation priorities. Offline & PDF-safe.
"""
from __future__ import annotations

from datetime import datetime, timezone

from lazyhound.finder.reports.html_unified_report import (
    STYLES, _THEME_VARS, _BASE_CSS, _SEV_COLOR, _e)
from lazyhound.finder.reports.findings_report import generate_findings_report
from lazyhound.finder.reports import svg

_GRADE_SCORE = {"A": 0.12, "B": 0.32, "C": 0.55, "D": 0.75, "F": 0.95}
_GRADE_COLOR = {"A": "#2f9e44", "B": "#82c91e", "C": "#f2c744", "D": "#f5871f", "F": "#e5484d"}

_CSS = """
.dash-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}
.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:16px 0}
.kpi{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);
box-shadow:var(--shadow);padding:16px;text-align:center}
.kpi .num{font-size:1.9rem;font-weight:800}
.kpi .lbl{color:var(--muted);font-size:.78rem;text-transform:uppercase;letter-spacing:.04em}
.panel{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin:14px 0}
.panel h3{margin:0 0 10px;font-size:.95rem}
.svg-donut-c{font-size:1.6rem;font-weight:800;fill:var(--text)}
.svg-gauge-c{font-size:2.4rem;font-weight:800;fill:var(--text)}
.svg-lab{font-size:.72rem;fill:var(--muted)}.svg-val{font-size:.72rem;font-weight:700;fill:var(--text)}
.svg-track{fill:rgba(127,127,127,.12)}
.rem{border-bottom:1px dashed var(--border);padding:8px 0}.rem:last-child{border:none}
.rem .bar{height:8px;border-radius:4px;background:var(--accent);margin-top:5px}
"""


def build_dashboard_html(result, domain: str = "", style: int = 1, generated: str | None = None) -> str:
    if style not in _THEME_VARS:
        style = 1
    rep = generate_findings_report(result)
    ts = generated or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = domain or rep.get("domain") or "unknown realm"
    grade = rep["grade"]
    sev = rep["severity_breakdown"]
    paths = rep.get("attack_paths", [])

    css = f":root{{{_THEME_VARS[style]}}}\n" + _BASE_CSS + _CSS
    o = ["<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
         "<meta name='viewport' content='width=device-width,initial-scale=1'>",
         f"<title>LazyHound Risk Dashboard — {_e(title)}</title>",
         f"<style>{css}</style></head><body class='style-{style}'><div class='wrap'>",
         f"<header class='rpt'><h1>Risk Dashboard</h1><div class='sub'>{_e(title)} · "
         f"generated {_e(ts)} · style {style} ({_e(STYLES[style])})</div></header>"]

    donut_segs = [(sev.get(s, 0), _SEV_COLOR.get(s, "#888"), s)
                  for s in ("critical", "high", "medium", "info")]
    o.append("<div class='dash-grid'>"
             f"<div class='panel'><h3>Risk grade</h3>"
             f"{svg.gauge(_GRADE_SCORE.get(grade, .5), grade, color=_GRADE_COLOR.get(grade, '#888'))}</div>"
             f"<div class='panel'><h3>Findings by severity</h3>"
             f"{svg.donut(donut_segs, center_label=str(rep['total_actionable']))}</div>"
             "</div>")

    kpis = [("Attack paths to Tier Zero", len(paths)),
            ("Critical findings", sev.get("critical", 0)),
            ("ATT&CK Techniques", len(rep.get("category_breakdown", {}))),
            ("Principals reaching Tier Zero", len({p["from"] for p in paths}))]
    o.append("<div class='kpis'>")
    for lbl, n in kpis:
        o.append(f"<div class='kpi'><div class='num'>{n}</div><div class='lbl'>{_e(lbl)}</div></div>")
    o.append("</div>")

    cats = sorted(rep.get("category_breakdown", {}).items(), key=lambda kv: -kv[1]["count"])[:10]
    rows = [(name, v["count"], _SEV_COLOR.get(v["max_severity"], "#888")) for name, v in cats]
    o.append(f"<div class='panel'><h3>Findings by category</h3>{svg.hbars(rows)}</div>")

    o.append("<div class='panel'><h3>Top Remediation Priorities</h3>")
    pr = rep.get("remediation_priorities", [])
    mx = max((p["finding_count"] for p in pr), default=1) or 1
    for i, p in enumerate(pr[:6], 1):
        w = round(p["finding_count"] * 100 / mx)
        o.append(f"<div class='rem'><strong>{i}. {_e(p['category'])}</strong> "
                 f"<span style='color:var(--muted)'>· {p['finding_count']} finding(s), "
                 f"{p['affected_objects']} object(s)</span>"
                 f"<div class='bar' style='width:{w}%'></div>"
                 f"<div style='color:var(--muted);font-size:.85rem;margin-top:4px'>{_e(p['remediation'])}</div></div>")
    o.append("</div>")

    o.append("<footer class='rpt'>Generated by LazyHound · executive risk dashboard</footer>"
             "</div></body></html>")
    return "\n".join(o)


def build_dashboard_markdown(result, domain: str = "") -> str:
    rep = generate_findings_report(result)
    title = domain or rep.get("domain") or "unknown"
    sev = rep["severity_breakdown"]
    paths = rep.get("attack_paths", [])
    lines = [f"# Risk Dashboard — {title}", "",
             f"**Grade: {rep['grade']}** · {rep['total_actionable']} actionable findings · "
             f"{len(paths)} path(s) to Tier Zero", "",
             "| KPI | Value |", "|---|---|",
             f"| Attack paths to Tier Zero | {len(paths)} |",
             f"| Critical findings | {sev.get('critical', 0)} |",
             f"| ATT&CK techniques | {len(rep.get('category_breakdown', {}))} |",
             f"| Principals reaching Tier Zero | {len({p['from'] for p in paths})} |", "",
             "| Severity | Count |", "|---|---|"]
    for s in ("critical", "high", "medium", "info"):
        if sev.get(s):
            lines.append(f"| {s.capitalize()} | {sev[s]} |")
    lines += ["", "| Category | Count | Max severity |", "|---|---|---|"]
    for name, v in sorted(rep.get("category_breakdown", {}).items(), key=lambda kv: -kv[1]["count"]):
        lines.append(f"| {name} | {v['count']} | {v['max_severity']} |")
    return "\n".join(lines)
