"""DOCX report renderer for the composable report builder.

Builds a Word document from report sections, optionally using a template.
When a template is provided, the builder replaces ``{{section:<key>}}``
placeholders with the section content.  When no template is provided, the
sections are rendered sequentially using built-in styles.

Requires: pip install python-docx
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .report_builder import ReportSection


def build_docx(
    sections: list[ReportSection],
    dest: Path,
    domain: str,
    template_path: str | None = None,
) -> Path:
    """Build a DOCX report and write to *dest*.

    If *template_path* is given and the file exists, the template is loaded
    and ``{{section:<key>}}`` markers are replaced with rendered content.
    Otherwise a fresh document is built from scratch.
    """
    try:
        from docx import Document
    except ImportError:
        raise RuntimeError(
            "DOCX export requires python-docx. Install with: pip install python-docx"
        )

    section_map = {s.key: s for s in sections}

    if template_path and Path(template_path).is_file():
        doc = _from_template(Document(template_path), section_map, domain)
    else:
        doc = _from_scratch(sections, domain)

    dest.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(dest))
    return dest


# ---------------------------------------------------------------------------
# Template-based rendering
# ---------------------------------------------------------------------------

_PLACEHOLDER_RE = re.compile(r"\{\{section:(\w+)\}\}")
_META_RE = re.compile(r"\{\{(\w+)\}\}")


def _from_template(
    doc,
    section_map: dict[str, ReportSection],
    domain: str,
) -> object:
    """Replace placeholders in an existing template document."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta = {"domain": domain, "date": now}

    for para in doc.paragraphs:
        text = para.text

        # Replace meta placeholders like {{domain}}, {{date}}
        if _META_RE.search(text):
            for key, val in meta.items():
                text = text.replace(f"{{{{{key}}}}}", val)
            # Clear existing runs and write the new text
            if text != para.text:
                for run in para.runs:
                    run.text = ""
                if para.runs:
                    para.runs[0].text = text
                else:
                    para.add_run(text)

        # Replace section placeholders
        match = _PLACEHOLDER_RE.search(para.text)
        if match:
            key = match.group(1)
            section = section_map.get(key)
            if section:
                # Clear the placeholder paragraph
                para.text = ""
                # Insert section content after this paragraph
                _insert_markdown_content(doc, para, section)
            else:
                para.text = f"(Section '{key}' not included in report)"

    return doc


def _insert_markdown_content(doc, anchor_para, section: ReportSection) -> None:
    """Parse markdown content and append paragraphs/tables after *anchor_para*."""
    from docx.shared import Pt

    lines = section.markdown.split("\n")
    insert_idx = _get_paragraph_index(doc, anchor_para)

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Skip the "---" and generator footer lines
        if stripped == "---" or stripped.startswith("*Report generated by"):
            continue

        # Headings
        if stripped.startswith("# "):
            level = 0
            text = stripped.lstrip("#").strip()
            while stripped[level] == "#":
                level += 1
            level = min(level, 3)
            p = doc.add_paragraph(text, style=f"Heading {level}")
            _move_paragraph_after(doc, p, insert_idx)
            insert_idx += 1

        # Table rows — accumulate and create table
        elif stripped.startswith("|"):
            # This is handled by the table builder below
            continue

        # Bold lines (finding entries like **1. [CRITICAL]** ...)
        elif stripped.startswith("**") and "**" in stripped[2:]:
            text = stripped.strip("*").strip()
            p = doc.add_paragraph()
            run = p.add_run(text)
            run.bold = True
            _move_paragraph_after(doc, p, insert_idx)
            insert_idx += 1

        # List items
        elif stripped.startswith("- "):
            text = stripped[2:]
            # Strip markdown bold markers
            text = text.replace("**", "")
            p = doc.add_paragraph(text, style="List Bullet")
            _move_paragraph_after(doc, p, insert_idx)
            insert_idx += 1

        # Normal text
        else:
            text = stripped.replace("`", "").replace("**", "")
            p = doc.add_paragraph(text)
            _move_paragraph_after(doc, p, insert_idx)
            insert_idx += 1

    # Handle tables: find contiguous | lines and build Word tables
    _insert_tables(doc, section.markdown, anchor_para)


def _get_paragraph_index(doc, para) -> int:
    """Find the index of *para* in the document body."""
    for i, p in enumerate(doc.paragraphs):
        if p._element is para._element:
            return i
    return len(doc.paragraphs)


def _move_paragraph_after(doc, para, index: int) -> None:
    """Move a paragraph element to appear after the paragraph at *index*."""
    body = doc.element.body
    paragraphs = list(body.iterchildren())
    try:
        body.remove(para._element)
        if index < len(paragraphs):
            paragraphs[index].addnext(para._element)
    except (ValueError, IndexError):
        pass


def _insert_tables(doc, markdown: str, anchor_para) -> None:
    """Find Markdown tables in *markdown* and insert them as Word tables."""
    from docx.shared import Pt, Inches

    lines = markdown.split("\n")
    table_blocks: list[list[str]] = []
    current_block: list[str] = []

    for line in lines:
        if line.strip().startswith("|"):
            current_block.append(line.strip())
        else:
            if current_block:
                table_blocks.append(current_block)
                current_block = []
    if current_block:
        table_blocks.append(current_block)

    for block in table_blocks:
        rows = []
        for row_line in block:
            # Skip separator rows like |---|---|
            if re.match(r"^\|[\s\-:|]+\|$", row_line):
                continue
            cells = [c.strip().replace("`", "").replace("**", "")
                     for c in row_line.split("|")[1:-1]]
            if cells:
                rows.append(cells)

        if not rows:
            continue

        # First row is the header
        n_cols = max(len(r) for r in rows)
        table = doc.add_table(rows=len(rows), cols=n_cols)
        table.style = "Table Grid"

        for i, row_data in enumerate(rows):
            for j, cell_text in enumerate(row_data):
                if j < n_cols:
                    table.rows[i].cells[j].text = cell_text

        # Bold the header row
        if rows:
            for cell in table.rows[0].cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.bold = True


# ---------------------------------------------------------------------------
# From-scratch rendering (no template)
# ---------------------------------------------------------------------------

def _from_scratch(sections: list[ReportSection], domain: str) -> object:
    """Build a complete DOCX document from sections without a template."""
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Style the document
    normal = doc.styles["Normal"]
    normal.font.size = Pt(11)
    normal.font.name = "Calibri"
    normal.paragraph_format.space_after = Pt(6)

    for level, size in [("Heading 1", 20), ("Heading 2", 16), ("Heading 3", 13)]:
        s = doc.styles[level]
        s.font.size = Pt(size)
        s.font.bold = True
        s.font.color.rgb = RGBColor(0x0F, 0x34, 0x60)

    # Cover page
    title = doc.add_paragraph("LazyHound", style="Title")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Security Assessment Report")
    run.font.size = Pt(16)
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"{domain}  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_page_break()

    # Table of Contents
    doc.add_heading("Table of Contents", level=1)
    for i, sec in enumerate(sections, 1):
        doc.add_paragraph(f"{i}. {sec.title}", style="List Number")
    doc.add_page_break()

    # Render each section
    for sec in sections:
        _render_section(doc, sec)
        doc.add_page_break()

    return doc


def _render_section(doc, section: ReportSection) -> None:
    """Render a single section's markdown into the document."""
    from docx.shared import Pt

    lines = section.markdown.split("\n")
    table_buffer: list[str] = []

    def flush_table():
        if not table_buffer:
            return
        _add_table_from_md(doc, table_buffer)
        table_buffer.clear()

    for line in lines:
        stripped = line.strip()

        # Table rows
        if stripped.startswith("|"):
            table_buffer.append(stripped)
            continue
        else:
            flush_table()

        if not stripped:
            continue

        # Skip footer
        if stripped == "---" or stripped.startswith("*Report generated by"):
            continue

        # Headings
        if stripped.startswith("###"):
            text = stripped.lstrip("#").strip()
            doc.add_heading(text, level=3)
        elif stripped.startswith("##"):
            text = stripped.lstrip("#").strip()
            doc.add_heading(text, level=2)
        elif stripped.startswith("#"):
            text = stripped.lstrip("#").strip()
            doc.add_heading(text, level=1)

        # Bold lines
        elif stripped.startswith("**") and "**" in stripped[2:]:
            text = stripped.replace("**", "").replace("`", "")
            p = doc.add_paragraph()
            run = p.add_run(text)
            run.bold = True

        # List items
        elif stripped.startswith("- "):
            text = stripped[2:].replace("**", "").replace("`", "")
            doc.add_paragraph(text, style="List Bullet")

        # Numbered list items
        elif re.match(r"^\d+\.\s", stripped):
            text = re.sub(r"^\d+\.\s", "", stripped).replace("**", "").replace("`", "")
            doc.add_paragraph(text, style="List Number")

        # Mermaid code blocks — add as code text
        elif stripped.startswith("```"):
            continue

        # Indented content (path chains, etc.)
        elif line.startswith("   "):
            text = stripped.strip().replace("`", "")
            p = doc.add_paragraph()
            run = p.add_run(text)
            run.font.size = Pt(9)

        # Normal paragraph
        else:
            text = stripped.replace("`", "").replace("**", "")
            doc.add_paragraph(text)

    flush_table()


def _add_table_from_md(doc, lines: list[str]) -> None:
    """Convert accumulated Markdown table lines into a Word table."""
    rows = []
    for row_line in lines:
        if re.match(r"^\|[\s\-:|]+\|$", row_line):
            continue
        cells = [c.strip().replace("`", "").replace("**", "")
                 for c in row_line.split("|")[1:-1]]
        if cells:
            rows.append(cells)

    if not rows:
        return

    n_cols = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=n_cols)
    table.style = "Table Grid"

    for i, row_data in enumerate(rows):
        for j, cell_text in enumerate(row_data):
            if j < n_cols:
                table.rows[i].cells[j].text = cell_text

    # Bold header row
    for cell in table.rows[0].cells:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
