"""Top Risks Leaderboard report (report run --type leaderboard).

Three ranked card columns — top attackers, most-targeted objects, fix-first
priorities — with medals and CSS bars. Offline & PDF-safe.
"""
from __future__ import annotations

from datetime import datetime, timezone

from lazyhound.finder.reports.html_unified_report import (
    STYLES, _THEME_VARS, _BASE_CSS, _SEV_COLOR, _e)
from lazyhound.finder.reports.findings_report import generate_findings_report

_MEDALS = {1: "🥇", 2: "🥈", 3: "🥉"}
_CSS = """
.lb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;margin:16px 0}
.lb-col{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow);padding:14px}
.lb-col h3{margin:0 0 10px;font-size:.95rem}
.lb-row{display:flex;align-items:center;gap:8px;padding:6px 0;border-bottom:1px dashed var(--border)}
.lb-row:last-child{border:none}
.lb-rank{width:24px;text-align:center;font-weight:800;color:var(--muted)}
.lb-name{flex:1;font-size:.9rem;word-break:break-word}
.lb-bar{height:8px;border-radius:4px;background:var(--accent);min-width:6px;display:block}
.lb-cnt{width:26px;text-align:right;font-weight:700;font-size:.85rem}
.lb-track{flex:0 0 90px;background:rgba(127,127,127,.12);border-radius:4px}
"""


def _rows(items, key, label_key, color_fn):
    mx = max((it[key] for it in items), default=1) or 1
    out = []
    for i, it in enumerate(items[:10], 1):
        rank = _MEDALS.get(i, str(i))
        w = round(it[key] * 100 / mx)
        out.append(f"<div class='lb-row'><span class='lb-rank'>{rank}</span>"
                   f"<span class='lb-name'>{_e(it[label_key])}</span>"
                   f"<span class='lb-track'><span class='lb-bar' style='width:{w}%;background:{color_fn(it)}'></span></span>"
                   f"<span class='lb-cnt'>{it[key]}</span></div>")
    return "".join(out) or "<div class='lb-row'><span class='lb-name muted'>none</span></div>"


def build_leaderboard_html(result, domain: str = "", style: int = 1, generated: str | None = None) -> str:
    if style not in _THEME_VARS:
        style = 1
    rep = generate_findings_report(result)
    ts = generated or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = domain or rep.get("domain") or "unknown realm"
    css = f":root{{{_THEME_VARS[style]}}}\n" + _BASE_CSS + _CSS
    acc = lambda it: "var(--accent)"
    sevc = lambda it: _SEV_COLOR.get(it.get("severity", ""), "var(--accent)")
    o = ["<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
         "<meta name='viewport' content='width=device-width,initial-scale=1'>",
         f"<title>LazyHound Top Risks — {_e(title)}</title>",
         f"<style>{css}</style></head><body class='style-{style}'><div class='wrap'>",
         f"<header class='rpt'><h1>Top Risks Leaderboard</h1><div class='sub'>{_e(title)} · "
         f"generated {_e(ts)}</div></header>",
         "<div class='lb-grid'>",
         f"<div class='lb-col'><h3>🥇 Top Attackers</h3>"
         f"{_rows(rep.get('top_attacking_principals', []), 'finding_count', 'name', acc)}</div>",
         f"<div class='lb-col'><h3>🎯 Most-Targeted</h3>"
         f"{_rows(rep.get('most_targeted_objects', []), 'finding_count', 'name', acc)}</div>",
         f"<div class='lb-col'><h3>🔧 Fix First</h3>"
         f"{_rows(rep.get('remediation_priorities', []), 'finding_count', 'category', sevc)}</div>",
         "</div>",
         "<footer class='rpt'>Generated by LazyHound · top risks</footer></div></body></html>"]
    return "\n".join(o)


def build_leaderboard_markdown(result, domain: str = "") -> str:
    rep = generate_findings_report(result)
    title = domain or rep.get("domain") or "unknown"
    lines = [f"# Top Risks — {title}", ""]
    for head, items, key, lab in [
            ("Top Attackers", rep.get("top_attacking_principals", []), "finding_count", "name"),
            ("Most-Targeted Objects", rep.get("most_targeted_objects", []), "finding_count", "name"),
            ("Fix First", rep.get("remediation_priorities", []), "finding_count", "category")]:
        lines += [f"## {head}", "", "| # | Name | Findings |", "|---|---|---|"]
        for i, it in enumerate(items[:10], 1):
            lines.append(f"| {i} | {it[lab]} | {it[key]} |")
        lines.append("")
    return "\n".join(lines)
