"""Markdown report writer — easy to paste into pentest reports and wikis."""

from __future__ import annotations

from pathlib import Path

from lazyhound.finder.finder_models import CheckCategory, ScanResult, Severity


class MarkdownReport:
    """Generate a Markdown report from scan results."""

    @staticmethod
    def to_string(result: ScanResult) -> str:
        return _render(result)

    @staticmethod
    def write(result: ScanResult, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(_render(result), encoding="utf-8")
        return p


def _render(r: ScanResult) -> str:
    sections: list[str] = []

    # Header
    sections.append(f"# LazyHound Security Assessment — {r.target_domain}\n")
    sections.append("| Field | Value |")
    sections.append("|-------|-------|")
    sections.append(f"| **Scan ID** | `{r.scan_id}` |")
    sections.append(f"| **Started** | {r.started_at:%Y-%m-%d %H:%M:%S} UTC |")
    sections.append(f"| **Duration** | {r.duration_ms:.0f} ms |")
    sections.append(f"| **Rating** | **{r.rating}** |")
    sections.append(f"| **Blended Score** | {r.risk_score}/100 |")
    sections.append(f"| **Health** | {r.health_pct:.0f}% ({r.total_objects - r.affected_object_count}/{r.total_objects} objects clean) |")
    sections.append(f"| **Raw Risk Score** | {r.raw_risk_score}/100 |")
    sections.append(f"| **Total Findings** | {r.total_findings} |")
    sections.append(f"| **Checks Passed** | {r.checks_passed}/{r.checks_passed + r.checks_failed} |")
    sections.append("")

    # Domain info
    di = r.domain_info
    if di.domain:
        sections.append("## Domain Information\n")
        sections.append("| Field | Value |")
        sections.append("|-------|-------|")
        sections.append(f"| Domain | `{di.domain}` |")
        sections.append(f"| Domain SID | `{di.domain_sid}` |")
        sections.append(f"| Functional Level | {di.functional_level} |")
        sections.append(f"| Users | {di.total_users} |")
        sections.append(f"| Computers | {di.total_computers} |")
        sections.append(f"| Groups | {di.total_groups} |")
        if di.domain_controllers:
            sections.append(f"| Domain Controllers | {', '.join(di.domain_controllers)} |")
        sections.append("")

    # Severity summary
    by_sev = r.findings_by_severity()
    sections.append("## Severity Summary\n")
    sections.append("| Severity | Count |")
    sections.append("|----------|-------|")
    for sev in Severity:
        count = len(by_sev.get(sev, []))
        if count:
            sections.append(f"| {sev.value.upper()} | {count} |")
    sections.append("")

    # Findings by category
    by_cat = r.findings_by_category()
    if by_cat:
        sections.append("## Findings by Category\n")
        for cat in CheckCategory:
            findings = by_cat.get(cat, [])
            if not findings:
                continue
            sections.append(f"### {cat.label} ({len(findings)} findings)\n")
            for f in sorted(findings, key=lambda x: x.severity.sort_order):
                sev_badge = f"`{f.severity.value.upper()}`"
                sections.append(f"#### [{f.check_id}] {f.title} {sev_badge}\n")
                sections.append(f"{f.description}\n")
                if f.affected_objects:
                    shown = f.affected_objects[:10]
                    sections.append(f"**Affected ({f.affected_count}):** `{', '.join(shown)}`")
                    if f.affected_count > 10:
                        sections.append(f" ... and {f.affected_count - 10} more")
                    sections.append("")
                if f.mitre:
                    m = f.mitre.to_dict()
                    sections.append(
                        f"**MITRE ATT&CK:** [{m['technique_id']} — {m['technique_name']}]({m['url']})\n"
                    )
                if f.remediation:
                    sections.append(f"**Remediation:** {f.remediation.description}\n")
                    if f.remediation.powershell:
                        sections.append(f"```powershell\n{f.remediation.powershell}\n```\n")

    # Errors
    errors = [cr for cr in r.check_results if cr.error]
    if errors:
        sections.append("## Errors\n")
        for cr in errors:
            sections.append(f"- **{cr.check_id}** ({cr.check_name}): {cr.error}")
        sections.append("")

    sections.append("---\n*Report generated by LazyHound*\n")
    return "\n".join(sections)
