"""Coverage Radar report (report run --type radar).

A single SVG radar of finding volume per category. Pure SVG/CSS, offline.
"""
from __future__ import annotations

from datetime import datetime, timezone

from lazyhound.finder.reports.html_unified_report import (
    STYLES, _THEME_VARS, _BASE_CSS, _SEV_COLOR, _e)
from lazyhound.finder.reports.attackpaths_report import _collect
from lazyhound.finder.reports import svg

_CSS = """
.radar-panel{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);
box-shadow:var(--shadow);padding:16px;margin:14px 0;text-align:center}
.radar-panel svg{max-width:420px}
.svg-radar-lab{font-size:10px;fill:var(--muted)}
.svg-radar-area{fill:var(--accent);fill-opacity:.30;stroke:var(--accent);stroke-width:2}
table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--border)}
"""


def _cat_counts(tech):
    return sorted(((cat.value, len(fs)) for cat, fs in tech.items()), key=lambda kv: -kv[1])[:8]


def build_radar_html(result, domain: str = "", style: int = 1, generated: str | None = None) -> str:
    if style not in _THEME_VARS:
        style = 1
    ts = generated or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    title = domain or getattr(result, "domain", "") or "unknown realm"
    _f, _p, tech = _collect(result)
    cats = _cat_counts(tech)
    css = f":root{{{_THEME_VARS[style]}}}\n" + _BASE_CSS + _CSS
    o = ["<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
         "<meta name='viewport' content='width=device-width,initial-scale=1'>",
         f"<title>LazyHound Coverage Radar — {_e(title)}</title>",
         f"<style>{css}</style></head><body class='style-{style}'><div class='wrap'>",
         f"<header class='rpt'><h1>Coverage Radar</h1><div class='sub'>{_e(title)} · "
         f"generated {_e(ts)} · axes = finding category, distance = finding volume</div></header>"]
    if not cats:
        o.append("<p class='muted'>No technique-mapped findings to chart.</p></div></body></html>")
        return "\n".join(o)
    labels = [c for c, _ in cats]
    values = [n for _, n in cats]
    o.append(f"<div class='radar-panel'>{svg.radar(labels, values)}</div>")
    o.append("<table><thead><tr><th>Category</th><th>Findings</th></tr></thead><tbody>")
    for c, n in cats:
        o.append(f"<tr><td>{_e(c)}</td><td>{n}</td></tr>")
    o.append("</tbody></table>")
    o.append("<footer class='rpt'>Generated by LazyHound · coverage radar</footer></div></body></html>")
    return "\n".join(o)


def build_radar_markdown(result, domain: str = "") -> str:
    title = domain or getattr(result, "domain", "") or "unknown"
    _f, _p, tech = _collect(result)
    lines = [f"# Coverage Radar — {title}", "", "| Category | Findings |", "|---|---|"]
    for c, n in _cat_counts(tech):
        lines.append(f"| {c} | {n} |")
    if not tech:
        lines.append("| _none_ | 0 |")
    return "\n".join(lines)
