"""Operator-editable report templates.

Each report type has a Markdown template in the project's ``templates/`` folder
that the operator can freely edit — rebrand with a logo, recolor, add cover
prose / notes / custom sections, and reorder the wrapper around the generated
report content. Templates use ``{{placeholder}}`` tokens (full-placeholder /
"style B" layout): scalars like ``{{domain}}`` or ``{{finding_count}}`` are
substituted, and ``{{content}}`` marks where the tool injects the generated
report body.

Design goals:
- **Editable by anyone** — plain Markdown + a small YAML settings block.
- **Never breaks output** — a missing template, field, or asset falls back to
  the built-in default; malformed input warns and degrades rather than raising.
- **Format-aware** — Markdown output stays Markdown; HTML/PDF get the colors,
  the embedded logo, and the operator's prose wrapped around the report.
"""

from __future__ import annotations

import base64
import html as _html
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

# Report types that get a template, with a human title used in defaults.
REPORT_TYPES: dict[str, str] = {
    "analyze": "Active Directory Attack-Path Assessment",
    "scan": "Active Directory Security Assessment",
    "heatmap": "MITRE ATT&CK Coverage Heatmap",
    "dashboard": "Executive Risk Dashboard",
    "graph": "Attack-Path Graph",
    "killchain": "Kill-Chain Analysis",
    "radar": "Findings Coverage Radar",
    "target": "Tier-Zero Exposure Rings",
    "leaderboard": "Top Risks Leaderboard",
}

# Template color field -> the CSS custom properties it overrides. Reports use
# two naming families (--sev-* in attackpaths-style reports, --* in the scan
# report), so each field drives both to recolor uniformly.
_COLOR_VARS: dict[str, tuple[str, ...]] = {
    "accent_color": ("--accent",),
    "critical_color": ("--sev-critical", "--critical"),
    "high_color": ("--sev-high", "--high"),
    "medium_color": ("--sev-medium", "--medium"),
    "low_color": ("--sev-low", "--low"),
    "info_color": ("--sev-info", "--info"),
    "background": ("--bg",),
    "text_color": ("--text",),
}

_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


def default_template(rtype: str) -> str:
    """Return the built-in default template text for *rtype* (style B)."""
    title = REPORT_TYPES.get(rtype, "LazyHound Report")
    return f"""\
---
# ── Report settings — edit freely. Delete any line to use the built-in default.
title: "{{{{domain}}}} — {title}"

# Branding (leave logo blank for none; path is relative to this templates/ folder)
logo: ""
footer: "Generated by LazyHound · {{{{date}}}}"
confidential: "CONFIDENTIAL — for authorized recipients only"

# Colors (HTML / PDF only; blank keeps the report theme's value)
accent_color:   "#e94560"
critical_color: "#dc3545"
high_color:     "#fd7e14"
medium_color:   "#ffc107"
low_color:      "#28a745"
info_color:     "#17a2b8"
background:     ""
text_color:     ""
---
{{{{logo}}}}

# {{{{title}}}}

_{{{{confidential}}}}_

<!-- Write any cover text, scope, or notes here — this whole file is yours. -->

{{{{content}}}}

---

{{{{footer}}}}
"""


def scaffold_templates(templates_dir: str | Path) -> list[Path]:
    """Create ``templates/`` (and ``templates/assets/``) and drop a default
    template for every report type. Existing templates are left untouched so an
    operator's edits are never overwritten. Returns the files written."""
    tdir = Path(templates_dir)
    tdir.mkdir(parents=True, exist_ok=True)
    (tdir / "assets").mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for rtype in REPORT_TYPES:
        path = tdir / f"{rtype}.md"
        if not path.exists():
            path.write_text(default_template(rtype), encoding="utf-8")
            written.append(path)
    return written


@dataclass
class ReportTemplate:
    """A parsed report template: YAML settings + a Markdown body."""

    settings: dict[str, Any] = field(default_factory=dict)
    body: str = ""
    base_dir: Path | None = None  # for resolving relative logo/asset paths

    # -- loading ------------------------------------------------------------

    @classmethod
    def load(cls, rtype: str, templates_dir: str | Path | None) -> "ReportTemplate | None":
        """Load ``templates/<rtype>.md``. Returns None (use built-in output) if
        no templates dir or file exists. Malformed YAML degrades to defaults."""
        if not templates_dir:
            return None
        path = Path(templates_dir) / f"{rtype}.md"
        if not path.is_file():
            return None
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError:
            return None
        return cls.parse(raw, base_dir=Path(templates_dir))

    @classmethod
    def parse(cls, raw: str, base_dir: Path | None = None) -> "ReportTemplate":
        settings: dict[str, Any] = {}
        body = raw
        m = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", raw, re.DOTALL)
        if m:
            try:
                loaded = yaml.safe_load(m.group(1)) or {}
                if isinstance(loaded, dict):
                    settings = loaded
            except yaml.YAMLError:
                settings = {}  # malformed front-matter -> ignore, keep body
            body = m.group(2)
        return cls(settings=settings, body=body, base_dir=base_dir)

    # -- rendering ----------------------------------------------------------

    def render(self, fmt: str, content: str, context: dict[str, Any]) -> str:
        """Render the template for *fmt* ('markdown'|'html'|'pdf'), injecting
        the generated report *content* at ``{{content}}`` and *context* scalars
        elsewhere. PDF is rendered exactly like HTML (WeasyPrint consumes it)."""
        ctx = self._scalar_context(context, fmt)
        if fmt == "markdown":
            return self._render_markdown(content, ctx)
        return self._render_html(content, ctx)

    def _scalar_context(self, context: dict[str, Any], fmt: str) -> dict[str, str]:
        """Build the {{token}} -> string map from context + settings."""
        ctx = {k: ("" if v is None else str(v)) for k, v in context.items()}
        # Interpolate settings text fields against the context (so a title of
        # "{{domain}} — Report" resolves), then expose them as tokens.
        for key in ("title", "footer", "confidential"):
            val = self.settings.get(key)
            if val is not None:
                ctx[key] = self._sub(str(val), ctx)
        ctx.setdefault("title", ctx.get("domain", "LazyHound Report"))
        ctx.setdefault("footer", "")
        ctx.setdefault("confidential", "")
        ctx["logo"] = self._logo_markup(fmt)
        return ctx

    @staticmethod
    def _sub(text: str, ctx: dict[str, str]) -> str:
        """Replace {{token}} with ctx[token]; unknown tokens become empty."""
        def repl(m: "re.Match[str]") -> str:
            return ctx.get(m.group(1).strip(), "")
        return re.sub(r"\{\{\s*([a-zA-Z0-9_]+)\s*\}\}", repl, text)

    def _render_markdown(self, content: str, ctx: dict[str, str]) -> str:
        ctx = dict(ctx)
        ctx["content"] = content
        return self._sub(self.body, ctx).strip() + "\n"

    def _render_html(self, content: str, ctx: dict[str, str]) -> str:
        # Split the operator's body at {{content}} into pre/post wrappers.
        parts = re.split(r"\{\{\s*content\s*\}\}", self.body, maxsplit=1)
        pre = self._sub(parts[0], ctx)
        post = self._sub(parts[1], ctx) if len(parts) > 1 else ""
        pre_html = _mini_markdown(pre)
        post_html = _mini_markdown(post)
        override = self._color_override_style()

        # Inject into the generated report document: color override into <head>,
        # the operator's pre/post wrappers just inside <body>. If the content
        # isn't a full HTML doc, wrap it so branding still applies.
        doc = content
        if "</head>" in doc:
            doc = doc.replace("</head>", override + "</head>", 1)
        else:
            doc = override + doc
        wrapper_css = _WRAPPER_CSS
        if re.search(r"<body[^>]*>", doc):
            doc = re.sub(r"(<body[^>]*>)",
                         lambda m: m.group(1) + wrapper_css
                         + f'<div class="lh-tpl-pre">{pre_html}</div>',
                         doc, count=1)
        else:
            doc = wrapper_css + f'<div class="lh-tpl-pre">{pre_html}</div>' + doc
        if "</body>" in doc:
            doc = doc.replace("</body>",
                              f'<div class="lh-tpl-post">{post_html}</div></body>', 1)
        else:
            doc = doc + f'<div class="lh-tpl-post">{post_html}</div>'
        return doc

    # -- helpers ------------------------------------------------------------

    def _color_override_style(self) -> str:
        decls: list[str] = []
        for field_name, css_vars in _COLOR_VARS.items():
            val = str(self.settings.get(field_name, "") or "").strip()
            if val and _HEX_RE.match(val):
                for var in css_vars:
                    decls.append(f"{var}:{val};")
        if not decls:
            return ""
        return "<style>:root{" + "".join(decls) + "}</style>"

    def _logo_markup(self, fmt: str) -> str:
        logo = str(self.settings.get("logo", "") or "").strip()
        if not logo:
            return ""
        path = Path(logo)
        if not path.is_absolute() and self.base_dir:
            path = self.base_dir / logo
        if fmt == "markdown":
            return f"![logo]({path})"
        # HTML/PDF: embed as a data URI so the report stays self-contained.
        try:
            data = path.read_bytes()
        except OSError:
            return ""
        ext = path.suffix.lower().lstrip(".") or "png"
        mime = "svg+xml" if ext == "svg" else ("jpeg" if ext in ("jpg", "jpeg") else ext)
        b64 = base64.b64encode(data).decode("ascii")
        return (f'<img class="lh-logo" alt="logo" '
                f'src="data:image/{mime};base64,{b64}">')


# CSS for the operator wrapper blocks, injected once into HTML/PDF output.
_WRAPPER_CSS = (
    "<style>.lh-tpl-pre,.lh-tpl-post{max-width:1100px;margin:1.5rem auto;"
    "padding:0 2rem;font-family:'Segoe UI',system-ui,sans-serif;}"
    ".lh-logo{max-height:80px;margin:1rem 0;}"
    ".lh-tpl-post{opacity:.85;font-size:.9rem;border-top:1px solid #8884;"
    "padding-top:1rem;}</style>"
)


def _mini_markdown(text: str) -> str:
    """Convert a small subset of Markdown to HTML for the operator's wrapper
    prose. Uses the 'markdown' package when available for full fidelity, else a
    minimal fallback (headings, images, bold/italic, paragraphs) — enough for
    logos, titles, and notes without a hard dependency."""
    text = text.strip()
    if not text:
        return ""
    try:
        import markdown as _md
        return _md.markdown(text, extensions=["tables"])
    except Exception:
        pass
    out: list[str] = []
    for block in re.split(r"\n\s*\n", text):
        block = block.strip()
        if not block:
            continue
        # Raw HTML (e.g. an embedded <img> logo) passes through untouched.
        if block.startswith("<"):
            out.append(block)
            continue
        h = re.match(r"^(#{1,6})\s+(.*)$", block)
        if h:
            lvl = len(h.group(1))
            out.append(f"<h{lvl}>{_inline_md(h.group(2))}</h{lvl}>")
        else:
            out.append(f"<p>{_inline_md(block)}</p>")
    return "\n".join(out)


def _inline_md(text: str) -> str:
    # Images first (before escaping), then bold/italic, then escape the rest.
    imgs: list[str] = []

    def _img(m: "re.Match[str]") -> str:
        imgs.append(f'<img alt="{_html.escape(m.group(1))}" src="{_html.escape(m.group(2))}">')
        return f"\x00{len(imgs) - 1}\x00"

    text = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", _img, text)
    text = _html.escape(text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"\x00(\d+)\x00", lambda m: imgs[int(m.group(1))], text)
    return text
