"""Verbose ``--help`` text for the collect / query / analyze menu commands.

Keyed ``"<submenu>:<cmd>"`` so ``show_detailed_help`` resolves each menu's own
help (a bare ``run``/``export``/``stats`` exists in several menus). Merged into
``_COMMAND_HELP`` by ``formatting.py``.
"""

MENU_HELP: dict[str, str] = {
    # ---------------------------------------------------------------- collect
    "collect:run": (
        "[bold]collect run[/bold] [--stealth low|med|high] [--nodisabled] [--slim] [--adcs] [--network]\n\n"
        "Run an authenticated LDAP collection from the configured Domain Controller\n"
        "and load the result into memory as the active collection. Connection,\n"
        "transport (SSL/StartTLS) and auth method are prompted interactively. The\n"
        "collection itself is strictly DCOnly; --adcs/--network chain the opt-in,\n"
        "host-touching enrichments right after it.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --adcs                  After the DCOnly collection, chain CA-host ADCS\n"
        "                          enrichment (same as 'collect adcs' → ESC6/7/8/11).\n"
        "  --network               After the DCOnly collection, chain the full SMB\n"
        "                          network crawl of all computers (same as\n"
        "                          'collect crawl --targets all' → sessions/local-admin).\n"
        "  --nodisabled            Drop disabled accounts from the collection.\n"
        "  --slim                  Trim object properties to analysis-relevant fields.\n"
        "  --stealth low|med|high  DCOnly LDAP pacing profile (default: low).\n"
        "                          ALL three collect the SAME full data (full\n"
        "                          security descriptors + full attributes); they\n"
        "                          differ only in LDAP query rate and two active\n"
        "                          side-lookups:\n"
        "                            low     no delay,  page 1000, ADCS+SRV on\n"
        "                            med     0.3s ±20%, page  500, ADCS+SRV off\n"
        "                            high    1.0s ±30%, page  300, ADCS+SRV off\n"
        "                          Slower pacing lowers the per-second request rate\n"
        "                          the DC sees. This affects 'collect run' only —\n"
        "                          host-touching SMB enumeration is 'collect crawl',\n"
        "                          which has its own throttles.\n\n"
        "[bold]Notes:[/bold]\n"
        "  DC, domain, username and the credential (password, nthash, or Kerberos\n"
        "  ccache) come from 'options' / stored creds.\n"
        "  Port, SSL/StartTLS and auth method are asked at run time.\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect run                     full-speed DCOnly collection (default 'low')\n"
        "  collect run --stealth med       same data, moderate LDAP pacing\n"
        "  collect run --adcs              DCOnly, then chain CA-host ADCS enrichment\n"
        "  collect run --adcs --network    DCOnly, then ADCS + full network crawl"
    ),
    "collect:crawl": (
        "[bold]collect crawl[/bold] [--targets all|dcs|servers|workstations] [--ou TEXT] "
        "[--batch-size N] [--smb-workers N] [--smb-timeout N] [--recheck] [--background]\n\n"
        "Enumerate live sessions and local-group (local-admin) membership across the\n"
        "computers in the loaded collection via SMB, then merge the results back in.\n"
        "Requires a loaded collection and SMB credentials (password, nthash, or a\n"
        "Kerberos ccache — same 'options' store). With no --targets/--ou the\n"
        "command shows an interactive target picker. Subcommands control a running job.\n"
        "For CA-host ADCS enrichment (ESC6/7/8/11) see 'collect adcs'.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --targets LIST   Comma-separated target classes: all, dcs (or\n"
        "                   domain-controllers), servers, workstations\n"
        "  --ou TEXT        Restrict targets to computers whose OU matches TEXT\n"
        "  --batch-size N   Hosts per batch (default: 50)\n"
        "  --smb-workers N  Concurrent SMB workers (default: 10)\n"
        "  --smb-timeout N  Per-host SMB timeout in seconds (default: 5)\n"
        "  --recheck        Re-enumerate hosts already collected in a prior crawl\n"
        "  --background     Start the crawl as a background job and return\n\n"
        "[bold]Incremental & reporting:[/bold]\n"
        "  Crawling is incremental — hosts enumerated in a prior run are skipped\n"
        "  (shown as 'Skipping N already-collected'); use --recheck to force a\n"
        "  re-crawl. The completion summary reports two distinct scopes:\n"
        "    'Crawl complete (this run)'  — only the hosts crawled just now\n"
        "                                   (plus how many were skipped)\n"
        "    'Cumulative (all runs)'      — the persisted tracker across every\n"
        "                                   crawl of the loaded collection\n"
        "  So a run that skips the only reachable host can read '0/N reachable'\n"
        "  this run while the cumulative line still shows it reachable.\n\n"
        "[bold]Subcommands:[/bold]\n"
        "  collect crawl status | collect crawl pause | collect crawl resume | collect crawl stop\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect crawl                              interactive target selection\n"
        "  collect crawl --targets dcs,servers        DCs + servers only\n"
        "  collect crawl --ou Workstations --recheck  re-crawl a specific OU\n"
        "  collect crawl --background --batch-size 25 run detached in smaller batches\n"
        "  collect crawl status                       show progress of the active job"
    ),
    "collect:adcs": (
        "[bold]collect adcs[/bold] [--smb-timeout N]\n\n"
        "CA-host ADCS enrichment of the loaded collection. Discovers the CA host(s)\n"
        "from the collection's pKIEnrollmentService objects and actively gathers the\n"
        "CA-host ESCs, merging the result so 'analyze'/'report' surface them offline:\n\n"
        "  ESC8   web enrollment reachable   — HTTP HEAD to http://<ca>/certsrv/\n"
        "  ESC6   EDITF_ATTRIBUTESUBJECTALTNAME2  — CA registry (PolicyModules)\n"
        "  ESC11  RPC encryption enforcement — CA registry (InterfaceFlags)\n"
        "  ESC7   Manage CA / Manage Certificates — CA registry (Security DACL)\n\n"
        "Requires a loaded collection and SMB credentials (same 'options' store).\n"
        "Only ESC8 is unauthenticated HTTP; ESC6/7/11 need the Remote Registry\n"
        "service running on the CA — if it's off, only the ESC8 result is stored\n"
        "(the registry fields stay unread, never a false verdict). This is the only\n"
        "host-touching ADCS step; 'collect run' stays DCOnly. Marks the collection\n"
        "DCOnly+ADCS (or +ADCS+Network). Remove it with 'collect clear --adcs'.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --smb-timeout N  Per-CA SMB/HTTP timeout in seconds (default: 5)\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect adcs                  enrich the loaded collection's CA host(s)\n"
        "  collect run --adcs            DCOnly collection, then chain ADCS enrichment"
    ),
    "collect:clear": (
        "[bold]collect clear[/bold] --sessions | --local-admins | --adcs | --all\n\n"
        "Strip crawl-derived data (collected by 'crawl') from the loaded\n"
        "collection. With no flag, an interactive menu lists current counts. Clearing\n"
        "sessions+local-admins also drops the crawl tracker and network stats.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --sessions       Remove collected logon-session data\n"
        "  --local-admins   Remove collected local-group / local-admin membership\n"
        "  --adcs           Remove CA-host ADCS enrichment (ESC6/7/8/11 data)\n"
        "  --all            Remove all of the above, plus the enumeration tracker\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect clear                 interactive prompt with current counts\n"
        "  collect clear --sessions      drop only session data\n"
        "  collect clear --adcs          drop only CA-host ADCS enrichment\n"
        "  collect clear --all           wipe all crawl-derived data"
    ),
    "collect:load": (
        "[bold]collect load[/bold] <collection_id|file_path>\n\n"
        "Load a previously stored collection and make it active. The argument is tried\n"
        "first as a stored collection_id in the database, then as a path to a lazyhound\n"
        "collection JSON file. Replaces any currently loaded collection.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  collection_id|file_path   A stored collection ID, or a path to a JSON file\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect load                          (no arg) prints usage and lists collections\n"
        "  collect load 3f9a2c1b                  load stored collection by ID\n"
        "  collect load ./corp_collection.json   load a collection from a file"
    ),
    "collect:unload": (
        "[bold]collect unload[/bold]\n\n"
        "Unload the current collection from memory and clear all derived caches\n"
        "(query index, analysis results, active domain). Stored collections in the\n"
        "database are not deleted.\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect unload"
    ),
    "collect:list": (
        "[bold]collect list[/bold]\n\n"
        "List collections stored in the database (ID, domain, object count, timestamp).\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect list"
    ),
    "collect:stats": (
        "[bold]collect stats[/bold]\n\n"
        "Show details about the currently loaded collection: domain, object counts by\n"
        "class, a per-realm breakdown (forest domains + Entra tenant), collection\n"
        "method, and any network-enumeration (crawl) data present.\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect stats"
    ),
    "collect:delete": (
        "[bold]collect delete[/bold] <collection_id> | --all\n\n"
        "Delete a stored collection from the database. With --all, every stored\n"
        "collection is deleted after a confirmation prompt.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  collection_id   The stored collection ID to delete\n"
        "  --all           Delete all stored collections (prompts for confirmation)\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect delete                 (no arg) prints usage and lists collections\n"
        "  collect delete 3f9a2c1b        delete one collection by ID\n"
        "  collect delete --all           delete every stored collection"
    ),
    "collect:export": (
        "[bold]collect export[/bold] [--bloodhound] [--azurehound] [--raw|--json] "
        "[--format bloodhound|azurehound|json] -o <path>\n\n"
        "Export the loaded (or picked) collection. With no format flag, an interactive\n"
        "menu offers JSON / BloodHound CE / AzureHound. AzureHound export requires the\n"
        "collection to contain Azure data.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --bloodhound        Export a BloodHound CE .zip\n"
        "  --azurehound        Export an AzureHound-format .json (Azure data only)\n"
        "  --raw / --json      Export the raw lazyhound collection JSON\n"
        "  --format FMT        Same as the flags: bloodhound | azurehound | json | raw\n"
        "  -o <path>           Output file path (prompted/defaulted if omitted)\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect export                              interactive format menu\n"
        "  collect export --bloodhound -o corp.zip     BloodHound CE archive\n"
        "  collect export --azurehound -o entra.json   AzureHound JSON (hybrid/Azure data)\n"
        "  collect export --raw -o collection.json     raw lazyhound collection JSON"
    ),
    "collect:import": (
        "[bold]collect import[/bold] <bloodhound.zip | bloodhound.json | lazyhound_collection.json>\n\n"
        "Import an external collection as a new saved collection and load it. Input is\n"
        "auto-detected: a .zip is treated as BloodHound CE; a JSON with a top-level\n"
        "'objects' list is used directly as a lazyhound collection; any other\n"
        "(BloodHound-shaped) JSON is routed through the BloodHound converter.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  path   A BloodHound CE .zip, a BloodHound JSON, or a lazyhound collection JSON\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect import                          (no arg) prints usage\n"
        "  collect import ./bloodhound_ce.zip      import a BloodHound CE archive\n"
        "  collect import ./users.json             import a BloodHound JSON file\n"
        "  collect import ./lazyhound_collection.json  re-import a lazyhound collection"
    ),
    "collect:azure": (
        "[bold]collect azure[/bold] <azurehound.json> | --run --tenant <id|domain> "
        "[--username <upn> | --device-code | --client-id <id>] [-o <file>]\n\n"
        "Ingest Entra/Azure data. Without --run, imports an existing AzureHound JSON\n"
        "file. With --run, lazyhound collects Entra live via Microsoft Graph — no\n"
        "external azurehound binary needed. Three auth methods (no app registration\n"
        "for the user ones — a well-known public client is used):\n\n"
        "[bold]Auth methods (pick one with --run):[/bold]\n"
        "  --username <upn>   Supplied-credential (ROPC) sign-in; prompts for the\n"
        "                     password. Falls back to device code if MFA is required.\n"
        "  --device-code      Print a code + URL; approve once in a browser (MFA-safe).\n"
        "  --client-id <id>   Service principal (client credentials); prompts for the\n"
        "                     secret (or --secret). Needs an app registration.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  azurehound.json    Path to an AzureHound JSON file (import mode)\n"
        "  --tenant <id|domain>  Tenant GUID or a domain (e.g. mydomain.onmicrosoft.com)\n"
        "  --password <pw>    Password for --username (omit to be prompted securely)\n"
        "  --secret <secret>  Client secret for --client-id (omit to be prompted)\n"
        "  --client-id <id>   Override the default public client (user flows) or the\n"
        "                     service-principal app id\n"
        "  -o <file>          Write the collected AzureHound JSON to this path\n\n"
        "[bold]Notes:[/bold]\n"
        "  Collection reflects what the account can read (Global Reader = full\n"
        "  directory read). ROPC needs a non-MFA, non-federated cloud account; use\n"
        "  --device-code otherwise.\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect azure ./azurehound.json                                  import an AzureHound file\n"
        "  collect azure --run --tenant mydomain.onmicrosoft.com --username bob@mydomain.local\n"
        "  collect azure --run --tenant mydomain.onmicrosoft.com --device-code\n"
        "  collect azure --run --tenant CONTOSO --client-id APPID -o entra.json   service principal"
    ),

    # ------------------------------------------------------------------ query
    "search:info": (
        "[bold]search info[/bold] <object> [--domain all|<fqdn>]\n\n"
        "Show the full details of a single directory object — identity, SID, DN,\n"
        "key attributes, and flags. Resolves by name, sAMAccountName, SID, or DN.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  object               The principal/object to look up (name, sAMAccountName,\n"
        "                       SID, or distinguishedName)\n"
        "  --domain all|<fqdn>  Scope resolution to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure' for the tenant). Default: the active\n"
        "                       domain (shown in the prompt, switch with 'domain').\n"
        "                       'all' = search every domain and print each match.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search info administrator              details for the active-domain admin\n"
        "  search info \"domain admins\"            look up a group by display name\n"
        "  search info S-1-5-21-...-512           resolve by SID\n"
        "  search info krbtgt --domain all        find krbtgt in every forest domain\n"
        "  search info svc-sql --domain globex.corp   look up in the GLOBEX realm"
    ),
    "search:members": (
        "[bold]search members[/bold] <group> [--recursive] [--domain all|<fqdn>]\n\n"
        "List the membership of a group. By default shows direct members only;\n"
        "add --recursive to expand nested groups into their effective members.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  group                The group to enumerate (name, sAMAccountName, SID, or DN)\n"
        "  --recursive          Expand nested groups and list all effective members\n"
        "  --domain all|<fqdn>  Scope to one realm (FQDN, NetBIOS, SID, or 'entra'/\n"
        "                       'azure'). Default: the active domain. 'all' = resolve\n"
        "                       the group in every domain and add a Domain column.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search members \"domain admins\"                direct members\n"
        "  search members \"domain admins\" --recursive    effective (nested) members\n"
        "  search members \"enterprise admins\" --domain all\n"
        "  search members \"server operators\" --domain globex.corp"
    ),
    "search:memberof": (
        "[bold]search memberof[/bold] <principal> [--recursive] [--domain all|<fqdn>]\n\n"
        "Show the groups a principal belongs to (reverse of 'members'). Add\n"
        "--recursive to follow transitive group nesting upward.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  principal            The user/computer/group to inspect (name, sAMAccountName,\n"
        "                       SID, or DN)\n"
        "  --recursive          Include groups gained through nested-group membership\n"
        "  --domain all|<fqdn>  Scope to one realm (FQDN, NetBIOS, SID, or 'entra'/\n"
        "                       'azure'). Default: the active domain. 'all' = resolve\n"
        "                       the principal in every forest domain.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search memberof administrator\n"
        "  search memberof administrator --recursive\n"
        "  search memberof svc-sql --domain globex.corp\n"
        "  search memberof jdoe --domain all"
    ),
    "search:acl": (
        "[bold]search acl[/bold] <object> [--domain all|<fqdn>]\n\n"
        "Dump the DACL of an object — every trustee and the rights they hold on it\n"
        "(GenericAll, WriteDacl, WriteOwner, resets, etc.). Useful for spotting\n"
        "abusable ACEs before pivoting to 'search who-can' or the analyze commands.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  object               The target object (name, sAMAccountName, SID, or DN)\n"
        "  --domain all|<fqdn>  Scope to one realm (FQDN, NetBIOS, SID, or 'entra'/\n"
        "                       'azure'). Default: the active domain. 'all' = print\n"
        "                       the DACL for the object in every domain it exists in.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search acl administrator\n"
        "  search acl \"domain admins\"\n"
        "  search acl AdminSDHolder --domain all\n"
        "  search acl gpo-default-policy --domain globex.corp"
    ),
    "search:who-can": (
        "[bold]search who-can[/bold] <right> <target> [--domain all|<fqdn>]\n\n"
        "List every principal that holds a given right over a target object — the\n"
        "inverse view of 'search acl'. Answers \"who can write/own/control this?\".\n\n"
        "[bold]Parameters:[/bold]\n"
        "  right                The right to search for (e.g. GenericAll, GenericWrite,\n"
        "                       WriteDacl, WriteOwner, ForceChangePassword, AllExtendedRights)\n"
        "  target               The object the right is held over (name, SID, or DN)\n"
        "  --domain all|<fqdn>  Scope to one realm (FQDN, NetBIOS, SID, or 'entra'/\n"
        "                       'azure'). Default: the active domain. 'all' = evaluate\n"
        "                       the target in every domain it exists in.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search who-can GenericAll \"domain admins\"\n"
        "  search who-can WriteDacl administrator\n"
        "  search who-can ForceChangePassword svc-sql --domain globex.corp\n"
        "  search who-can GenericWrite \"enterprise admins\" --domain all"
    ),
    "search:custom": (
        "[bold]search custom[/bold] <filter> [attrs] [--domain all|<fqdn>]\n\n"
        "Find objects by attribute value. Accepts an LDAP-style 'attr=value' filter\n"
        "(parens optional) or an 'attr' plus a separate value/pattern; '*' wildcards\n"
        "are supported and the pattern defaults to '*' (any value present).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  filter               Either 'attr=value' (e.g. objectClass=user) or just an\n"
        "                       attribute name when a pattern follows\n"
        "  attrs                Optional value/pattern when not using 'attr=value'\n"
        "                       (e.g. 'search custom description *admin*')\n"
        "  --domain all|<fqdn>  Scope results to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure'). Default: the active domain. 'all' =\n"
        "                       search the whole forest.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search custom objectClass=user --domain all\n"
        "  search custom servicePrincipalName=*\n"
        "  search custom description *admin*\n"
        "  search custom \"(userAccountControl=4194304)\"   AS-REP-roastable accounts\n"
        "  search custom operatingSystem *2012*"
    ),
    "search:graph": (
        "[bold]search graph[/bold] <source> [--depth N] [--weighted]\n\n"
        "Render an attack-path graph rooted at a source principal. This view is\n"
        "driven by the graph engine — for full pathfinding use the 'analyze'\n"
        "commands (analyze run, analyze shortest, analyze export).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  source       The starting principal for the path graph (name, SID, or DN)\n"
        "  --depth N    Limit traversal to N hops from the source\n"
        "  --weighted   Use edge weights (attack cost) when ranking paths\n\n"
        "[bold]Examples:[/bold]\n"
        "  search graph jdoe\n"
        "  search graph svc-sql --depth 4\n"
        "  search graph \"domain users\" --weighted\n"
        "  search graph bob --depth 3 --weighted"
    ),
    "search:kerberoastable": (
        "[bold]search kerberoastable[/bold] [--domain all|<fqdn>]\n\n"
        "List accounts that are kerberoastable — user accounts with a Service\n"
        "Principal Name (SPN), whose service tickets can be requested and cracked\n"
        "offline. Pairs with the analyze/validate kerberoast checks.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --domain all|<fqdn>  Scope the listing to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure'). Default: the active domain. 'all' =\n"
        "                       forest-wide, adding a Domain column.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search kerberoastable\n"
        "  search kerberoastable --domain all\n"
        "  search kerberoastable --domain globex.corp"
    ),
    "search:delegation-map": (
        "[bold]search delegation-map[/bold] [--domain all|<fqdn>]\n\n"
        "List every Kerberos delegation relationship in the collection —\n"
        "unconstrained, constrained (with target SPNs), and resource-based\n"
        "constrained delegation (RBCD) — for spotting impersonation pivots.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --domain all|<fqdn>  Scope the listing to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure'). Default: the active domain. 'all' =\n"
        "                       forest-wide, adding a Domain column.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search delegation-map\n"
        "  search delegation-map --domain all\n"
        "  search delegation-map --domain globex.corp"
    ),
    "search:computers": (
        "[bold]search computers[/bold] [--os-filter TEXT] [--domain all|<fqdn>]\n\n"
        "List computer objects in the collection, optionally narrowed to a given\n"
        "operating system. Handy for finding legacy/EOL hosts or sizing a domain.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --os-filter TEXT     Substring/pattern matched against the operatingSystem\n"
        "                       attribute (e.g. 2012, 'Windows 7', Server)\n"
        "  --domain all|<fqdn>  Scope the listing to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure'). Default: the active domain. 'all' =\n"
        "                       forest-wide, adding a Domain column.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search computers\n"
        "  search computers --os-filter 2012\n"
        "  search computers --os-filter \"Windows 7\"\n"
        "  search computers --domain all\n"
        "  search computers --os-filter Server --domain globex.corp"
    ),
    "search:trusts": (
        "[bold]search trusts[/bold]\n\n"
        "List the domain/forest trust relationships discovered in the collection —\n"
        "direction, transitivity, and trust type — to map cross-realm reach.\n"
        "Trusts are inherently forest-wide, so this listing is not domain-scoped.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search trusts"
    ),
    "search:templates": (
        "[bold]search templates[/bold]\n\n"
        "List the AD Certificate Services (ADCS) certificate templates in the\n"
        "collection — enrollment settings and flags relevant to ESC abuse. Pair\n"
        "with the analyze ADCS checks to find exploitable templates.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search templates"
    ),
    "search:spns": (
        "[bold]search spns[/bold] [--domain all|<fqdn>]\n\n"
        "List objects that have one or more Service Principal Names registered —\n"
        "the SPN inventory behind kerberoasting and service-account mapping.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --domain all|<fqdn>  Scope the listing to one realm (FQDN, NetBIOS, SID, or\n"
        "                       'entra'/'azure'). Default: the active domain. 'all' =\n"
        "                       forest-wide, adding a Domain column.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search spns\n"
        "  search spns --domain all\n"
        "  search spns --domain globex.corp"
    ),
    "search:stats": (
        "[bold]search stats[/bold]\n\n"
        "Print a summary of the loaded collection — object counts by class and other\n"
        "roll-ups — for a quick sense of size and coverage. Reports across the whole\n"
        "collection, so it is not domain-scoped.\n\n"
        "[bold]Examples:[/bold]\n"
        "  search stats"
    ),

    # ---------------------------------------------------------------- analyze
    "analyze:shortest": (
        "[bold]analyze shortest[/bold] [--from USER] [--to TARGET] [--depth N] "
        "[--domain all|<fqdn>]\n\n"
        "Shortest privilege-escalation paths TO Tier-Zero / high-value targets. "
        "A pathfinding command: with no --domain it searches across ALL realms.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --from USER          Start from this principal (re-runs scoped so owned-\n"
        "                       principal paths apply, not just a name filter)\n"
        "  --to TARGET          Keep only paths whose target name matches TARGET\n"
        "  --depth N            Drop paths longer than N hops\n"
        "  --domain all|<fqdn>  Realm to search (an AD domain or an Entra tenant —\n"
        "                       'entra'/'azure'/the onmicrosoft FQDN/tenant GUID).\n"
        "                       Omit to search EVERY realm; 'all' is also forest-wide;\n"
        "                       a single <fqdn> narrows to that realm's source principals.\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze shortest                       all paths to high-value targets, every realm\n"
        "  analyze shortest --from jack           paths starting from 'jack'\n"
        "  analyze shortest --from jack --domain globex.corp   only GLOBEX source principals\n"
        "  analyze shortest --to \"domain admins\"  paths whose target is Domain Admins\n"
        "  analyze shortest --depth 3             only paths of 3 hops or fewer"
    ),
    "analyze:trace": (
        "[bold]analyze trace[/bold] --to <target> [--from <source>] [--depth N] "
        "[--domain all|<fqdn>]\n\n"
        "Shortest path(s) to ANY target object (not just Tier Zero) — name or SID. "
        "A pathfinding command: with no --domain it searches across ALL realms.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --to <target>        Required. Destination object by name or SID\n"
        "  --from <source>      Restrict to paths that start at this principal\n"
        "  --depth N            Cap the path length at N hops\n"
        "  --domain all|<fqdn>  Realm to search (an AD domain or an Entra tenant).\n"
        "                       Omit (or 'all') to search EVERY realm; a single <fqdn>\n"
        "                       narrows the search and disambiguates --from/--to names\n"
        "                       to that realm's object.\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze trace --to \"domain admins\"           shortest path(s) to Domain Admins\n"
        "  analyze trace --to \"domain admins\" --from bob paths from 'bob' to Domain Admins\n"
        "  analyze trace --to FILESERVER01 --depth 4    routes to that host within 4 hops\n"
        "  analyze trace --to S-1-5-21-...-512 --domain globex.corp   scope to one realm"
    ),
    "analyze:paths": (
        "[bold]analyze paths[/bold] [--show] [--category CAT[,CAT2,...]] [--severity SEV] "
        "[--top N] [--show-inherited] [--domain all|<fqdn>]\n\n"
        "By default shows the compact per-category summary from the last 'analyze run'. "
        "Add [bold]--show[/bold] (or filters) to expand into the full finding "
        "tables. Re-slices the stored result (no re-analysis).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --show               Expand the summary into the full per-category tables\n"
        "  --category CAT[,...]  Show only these categories — a comma-separated list\n"
        "                       (e.g. dcsync, or dcsync,shortest_path, or acl,adcs)\n"
        "  --severity SEV       Show only this severity (critical|high|medium|info)\n"
        "  --top N              Show the N highest-priority findings\n"
        "  --show-inherited     Include inherited ACEs (hidden by default)\n"
        "  --domain all|<fqdn>  Scope to one realm in a multi-domain (forest)\n"
        "                       collection. Default: the active realm; 'all' =\n"
        "                       forest-wide. Filters which findings show — never\n"
        "                       re-analyzes the graph.\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze paths                              compact summary, active realm\n"
        "  analyze paths --show                       every category's findings\n"
        "  analyze paths --show --category dcsync     only DCSync findings\n"
        "  analyze paths --show --category dcsync,shortest_path   those two categories\n"
        "  analyze paths --severity critical --top 10   the 10 worst critical findings\n"
        "  analyze paths --show --domain all          full findings, forest-wide"
    ),
    "analyze:graph": (
        "[bold]analyze graph[/bold] [paths|blast|trusts]\n\n"
        "Render an attack diagram as ASCII in the terminal from the last 'analyze run'. "
        "Defaults to 'paths'. Dense diagrams (delegation, graph) are SVG-only — "
        "use 'analyze export --format svg --type <kind>'.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  paths    Privilege-escalation paths to high-value targets (default)\n"
        "  blast    Blast radius from owned principals (needs 'analyze run --owned ...')\n"
        "  trusts   Domain/forest trust relationships\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze graph              ASCII path diagram (same as 'analyze graph paths')\n"
        "  analyze graph blast        blast-radius diagram from owned principals\n"
        "  analyze graph trusts       domain trust relationships"
    ),
    "analyze:find": (
        "[bold]analyze find[/bold] <predicates> [--reaches <target|tier0>] [--from <source>]\n\n"
        "Ad-hoc graph query: list objects by attribute and/or reachability. "
        "Predicates are space- or comma-separated and combine (AND).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  <predicates>         type:user|computer|group|ou|gpo, kerberoastable, asrep,\n"
        "                       unconstrained, enabled, disabled, admincount, tier0,\n"
        "                       name:<substr>\n"
        "  --reaches <target>   Keep only objects that can reach <target> (or 'tier0')\n"
        "  --from <source>      Keep only objects reachable FROM <source>\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze find kerberoastable                  all kerberoastable accounts\n"
        "  analyze find type:computer unconstrained     unconstrained-delegation hosts\n"
        "  analyze find type:user --reaches tier0       users with a path to Tier Zero\n"
        "  analyze find admincount --from jack          admin objects reachable from 'jack'\n"
        "  analyze find name:sql type:user              users whose name contains 'sql'"
    ),
    "analyze:export": (
        "[bold]analyze export[/bold] --format <json|csv|ascii|mermaid|dot|svg|png> [--type KIND] "
        "[--category CAT] [--severity SEV] [--from ACCT] [--to TARGET] "
        "[--domain all|<fqdn>] -o <path>\n\n"
        "Export analysis results or a diagram from the last 'analyze run'. Two diagram modes: "
        "a PATH diagram (--from/--to) and a FINDINGS diagram (--category/--severity). "
        "json/csv export the actionable findings table, honoring "
        "--category / --severity / --from / --domain.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --format FMT         json, csv (data) or ascii, mermaid, dot, svg, png (diagram)\n"
        "  --type KIND          Diagram kind: paths, blast, trusts, delegation, graph\n"
        "                       (default: paths)\n"
        "  --category CAT       FINDINGS mode: draw findings of this category (e.g.\n"
        "                       laps_read, kerberoast) — even single-edge, non-path findings\n"
        "  --severity SEV       FINDINGS mode: draw findings of this severity\n"
        "  --from ACCT          PATH mode: scope to ACCT's path to its nearest Tier-Zero\n"
        "                       target. In FINDINGS mode, narrows to that principal.\n"
        "  --to TARGET          PATH mode: route to this named target (overrides nearest\n"
        "                       Tier Zero)\n"
        "  --domain all|<fqdn>  Realm scope (an AD domain or an Entra tenant). Omit (or\n"
        "                       'all') to span EVERY realm; a single <fqdn> narrows and\n"
        "                       disambiguates --from/--to names to that realm.\n"
        "  -o <path>            Output file (auto-named by mode/format when omitted)\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze export --format json -o findings.json        full findings as JSON\n"
        "  analyze export --from jack --format png -o jack.png   jack's path to Tier Zero\n"
        "  analyze export --from bob --to \"domain admins\" --format svg -o path.svg\n"
        "  analyze export --category laps_read --format png -o laps.png   LAPS-read findings\n"
        "  analyze export --type trusts --format svg -o trusts.svg        trust diagram"
    ),
    "analyze:checks": (
        "[bold]analyze checks[/bold]\n\n"
        "List every available attack-path analysis check with its description and "
        "category. Use the names to scope an 'analyze run' via --checks / --exclude.\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze checks                         list all analysis checks\n"
        "  analyze run --checks shortest-path     then run only a check you saw listed\n"
        "  analyze run --exclude kerberoast       or skip one"
    ),
    "analyze:run": (
        "[bold]analyze run[/bold] [--checks CHK[,...]] [--exclude CHK[,...]] "
        "[--category CAT[,...]] [--owned USER[,...]] [--notier0] [--prune] "
        "[--noexpand] [--expand-cap N] [--aggregate SLUG[,...]] [--domain all|<fqdn>]\n\n"
        "Run graph-based attack-path analysis over the loaded collection and store the\n"
        "result. Afterwards drill in with 'analyze paths', 'analyze shortest',\n"
        "'analyze trace', 'analyze graph' (ASCII attack graph) and 'analyze export' —\n"
        "no re-analysis needed.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --checks CHK[,...]      Run only these analysis checks (see 'analyze checks')\n"
        "  --exclude CHK[,...]     Skip these checks\n"
        "  --category CAT[,...]    Limit to these finding categories\n"
        "  --owned USER[,...]      Mark these principals as owned (enables blast-radius)\n"
        "  --notier0              Hide low-signal Tier-Zero-actor / Exchange findings\n"
        "                         (shown by default)\n"
        "  --prune                Restrict analysis to the Tier-Zero-reachable subgraph\n"
        "  --noexpand             Do not expand groups into per-member findings\n"
        "  --expand-cap N         Cap projected expanded findings before rolling up\n"
        "                         (0 = never roll up; also LAZYHOUND_EXPAND_CAP env var)\n"
        "  --aggregate SLUG[,...]  Roll up these finding categories (by category slug)\n"
        "  --domain all|<fqdn>    Scope the printed SUMMARY to one realm ('all' =\n"
        "                         forest-wide). Affects the summary only; the full\n"
        "                         result is still stored for re-slicing.\n\n"
        "[bold]Examples:[/bold]\n"
        "  analyze run                          full analysis, active-realm summary\n"
        "  analyze run --checks shortest-path   only one check\n"
        "  analyze run --exclude kerberoast     skip a check\n"
        "  analyze run --owned jdoe,svc-sql     mark owned principals (blast radius)\n"
        "  analyze run --prune --domain all     Tier-Zero subgraph, forest-wide summary"
    ),

    # ------------------------------------------------------------------- scan
    "scan:run": (
        "[bold]scan run[/bold] [--category CAT[,...]] [--check ID[,...]] "
        "[--exclude ID[,...]] [--profile strict|balanced|lenient] [--no-collection]\n\n"
        "Run a live Active Directory security assessment against the configured DC.\n"
        "When a collection is loaded it is used to prioritise findings (Tier-Zero-\n"
        "aware); pass --no-collection to scan without it. Connection details (port,\n"
        "SSL/StartTLS, auth method) are prompted interactively at run time.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --category CAT[,...]  Run only checks in these categories (comma-separated)\n"
        "  --check ID[,...]      Run only these specific check IDs (comma-separated)\n"
        "  --exclude ID[,...]    Skip these check IDs (comma-separated)\n"
        "  --profile NAME       One-off scoring profile (strict|balanced|lenient),\n"
        "                       overriding the 'scoring:' config for this run only.\n"
        "                       See 'scan scoring'.\n"
        "  --no-collection      Scan live only; ignore the loaded collection\n\n"
        "[bold]Notes:[/bold]\n"
        "  DC/domain/username and the credential (password, nthash, or Kerberos\n"
        "  ccache) come from 'options' or stored creds; port,\n"
        "  SSL/StartTLS and auth method are asked interactively. Use 'scan checks' to\n"
        "  list check IDs and categories.\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan run                              full scan, collection-aware if loaded\n"
        "  scan run --category kerberos,adcs     only those categories\n"
        "  scan run --check ADCS-ESC1            a single check by ID\n"
        "  scan run --exclude password_policy    everything except that category/check\n"
        "  scan run --no-collection              live-only scan, ignore the collection"
    ),
    "scan:checks": (
        "[bold]scan checks[/bold] [category]\n\n"
        "List the available security-scan checks — ID, name, category and tags.\n"
        "An optional category argument filters the list (case-insensitive).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  category   Optional category to filter by (e.g. kerberos, adcs, delegation)\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan checks                list every check\n"
        "  scan checks kerberos       only Kerberos-category checks"
    ),
    "scan:list": (
        "[bold]scan list[/bold]\n\n"
        "List past scans stored in the scan-history database — scan ID, domain, user,\n"
        "date, risk score, rating and finding count. Use a scan ID with 'scan show',\n"
        "'scan diff', 'scan export' or 'scan delete'. Takes no arguments.\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan list"
    ),
    "scan:show": (
        "[bold]scan show[/bold] [scan_id]\n\n"
        "Re-render a stored scan's full results to the console. With no scan_id, shows\n"
        "the most recent scan from this session (if any); otherwise looks up the id.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  scan_id   Optional stored scan ID (from 'scan list'). Omit to show the last run.\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan show                   re-render the most recent scan\n"
        "  scan show 338e4aeff756      re-render a specific stored scan"
    ),
    "scan:delete": (
        "[bold]scan delete[/bold] <scan_id> | --all\n\n"
        "Delete a stored scan from the scan history. With --all, every stored scan is\n"
        "removed after a confirmation prompt.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  scan_id   The stored scan ID to delete (from 'scan list')\n"
        "  --all     Delete all stored scans (prompts for confirmation)\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan delete                 (no arg) prints usage\n"
        "  scan delete 338e4aeff756    delete one scan by ID\n"
        "  scan delete --all           delete every stored scan"
    ),
    "scan:diff": (
        "[bold]scan diff[/bold] <old_scan_id> <new_scan_id>\n\n"
        "Compare two stored scans and show what changed — score delta, newly\n"
        "introduced findings, resolved findings and unchanged count. Both IDs required.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  old_scan_id   The earlier ('before') scan ID\n"
        "  new_scan_id   The later ('after') scan ID\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan diff 338e4aeff756 9f2c1b7a44e0"
    ),
    "scan:export": (
        "[bold]scan export[/bold] [scan_id] [--format json] [-o <path>]\n\n"
        "Export a stored scan's results to a file. With no scan_id an interactive\n"
        "picker opens (defaulting to the most recent scan).\n\n"
        "[bold]Parameters:[/bold]\n"
        "  scan_id       Optional stored scan ID; omit to pick interactively\n"
        "  --format FMT  Output file extension/label (default: json). The exported body\n"
        "                is JSON regardless — --format only sets the filename suffix.\n"
        "  -o <path>     Output path (default: <project>/exports/scan_results_<id>_<ts>.<fmt>,\n"
        "                then confirmed)\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan export                                 pick a scan, default JSON path\n"
        "  scan export 338e4aeff756 -o corp_scan.json  export a specific scan"
    ),
    "scan:scoring": (
        "[bold]scan scoring[/bold] [--profile strict|balanced|lenient]\n\n"
        "Show the scoring/grading model that 'scan run' will use — the profile,\n"
        "curve/coefficient, health blend, and the A/B/C/D grade thresholds (below\n"
        "D = F). Read-only; customise it in the 'scoring:' section of the project\n"
        "lazyhound.yml, or override the profile for a single run with\n"
        "'scan run --profile'.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --profile NAME   Preview the model as if this profile were active\n\n"
        "[bold]Config (lazyhound.yml):[/bold]\n"
        "  scoring:\n"
        "    profile: balanced                 # strict | balanced | lenient\n"
        "    grade_thresholds: {A: 90, B: 75, C: 60, D: 40}\n"
        "    curve: sqrt                        # linear | sqrt | log\n"
        "    coefficient: 5.5\n"
        "    health_weight: 0.4\n"
        "    severity_points: {critical: 40, high: 20, medium: 8, low: 2}\n"
        "    category_weights: {kerberos: 1.5, adcs: 1.4}\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan scoring\n"
        "  scan scoring --profile strict\n"
        "  scan run --profile lenient"
    ),
    "scan:options": (
        "[bold]scan options[/bold] [key=value ...] | all | clear\n\n"
        "View or set connection settings. This is the SAME settings store as the\n"
        "global 'options' command. With no arguments it shows only the settings\n"
        "you've set; 'scan options all' shows every setting including defaults.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  key=value   Set a value (e.g. dc=10.0.0.1). An empty value (key=) clears it.\n"
        "  all         Show every setting, including defaults\n"
        "  clear       Reset the connection keys (dc, domain, username, password, ...)\n\n"
        "[bold]Connection keys:[/bold]\n"
        "  dc, domain, username, port, auth_method, use_ssl, use_start_tls,\n"
        "  validate_cert, timeout, nameserver\n"
        "[bold]Credential[/bold] (mutually exclusive — one at a time):\n"
        "  password | nthash (32-hex or LM:NT) | ccache (Kerberos cache path)\n\n"
        "[bold]Examples:[/bold]\n"
        "  scan options\n"
        "  scan options dc=10.0.0.1 domain=corp.local username=admin\n"
        "  scan options all"
    ),

    # ------------------------------------------------------------------ report
    "report:run": (
        "[bold]report run[/bold] [--type TYPE] [--id <scan_id>] "
        "[--format html|pdf|markdown] [--style 1-5] [-o <path>]\n\n"
        "Build a report from the current analyze/scan data. Every report type except\n"
        "'scan' draws on the last 'analyze run' (you'll be offered to run it if\n"
        "missing); --type scan uses the last 'scan run', or a stored scan via --id.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  --type TYPE   Report to build (default: analyze). One of: analyze, scan,\n"
        "                heatmap, dashboard, graph, killchain, radar, target,\n"
        "                leaderboard. Common aliases work (paths->analyze,\n"
        "                exec->dashboard, mitre->heatmap, kill-chain->killchain, ...).\n"
        "  --id <scan_id>  (--type scan only) report on a stored scan instead of the\n"
        "                last in-memory run. List ids with 'scan list'.\n"
        "  --format FMT  Output format: html (default), pdf, or markdown (md)\n"
        "  --style 1-5   Visual style/theme, 1-5 (default: 1)\n"
        "  -o <path>     Output file (default:\n"
        "                <project>/reports/report_<domain>_<type>.<ext>)\n\n"
        "[bold]Examples:[/bold]\n"
        "  report run                                 analyze report, HTML\n"
        "  report run --type scan --format pdf        scan report (last run) as PDF\n"
        "  report run --type scan --id 7bae41df6830   report on a stored scan\n"
        "  report run --type heatmap --style 3        MITRE heatmap, style 3\n"
        "  report run --type dashboard -o exec.html   executive dashboard to a path"
    ),

    # ----------------------------------------------------------- collect options
    "collect:options": (
        "[bold]collect options[/bold] [key=value ...] | all | clear\n\n"
        "View or set connection settings. This is the SAME settings store as the\n"
        "global 'options' command. With no arguments it shows only the settings\n"
        "you've set; 'collect options all' shows every setting including defaults.\n\n"
        "[bold]Parameters:[/bold]\n"
        "  key=value   Set a value (e.g. dc=10.0.0.1). An empty value (key=) clears it.\n"
        "  all         Show every setting, including defaults\n"
        "  clear       Reset the connection keys (dc, domain, username, password, ...)\n\n"
        "[bold]Connection keys:[/bold]\n"
        "  dc, domain, username, port, auth_method, use_ssl, use_start_tls,\n"
        "  validate_cert, timeout, nameserver\n"
        "[bold]Credential[/bold] (mutually exclusive — one at a time):\n"
        "  password | nthash (32-hex or LM:NT) | ccache (Kerberos cache path)\n\n"
        "[bold]Examples:[/bold]\n"
        "  collect options\n"
        "  collect options dc=10.0.0.1 domain=corp.local username=admin\n"
        "  collect options all"
    ),

    # ---------------------------------------------------------------- version
    "version": (
        "[bold]version[/bold]\n\n"
        "Show the LazyHound version and banner. Takes no arguments.\n\n"
        "[bold]Examples:[/bold]\n"
        "  version"
    ),
}
